/**
 * BESS Machine Configuration
 */

import { Bess } from '../../models/Bess';
import type { MachineConfig, MachineParameter, MachinePreset, BessParams } from '../../types';
import { HARMONIC_PARAMETERS, DEFAULT_HARMONIC_PARAMS } from '../harmonic-params';

export const DEFAULT_BESS_PARAMS: BessParams = {
  voltage: 400,
  frequency: 50,
  powerRated: 100,
  energyCapacity: 200,
  powerSetpoint: 0,
  reactiveSetpoint: 0,
  socInitial: 50,
  efficiency: 95,
  priorityMode: 'active',
  ...DEFAULT_HARMONIC_PARAMS,
};

export const BESS_PARAMETERS: MachineParameter[] = [
  {
    key: 'voltage',
    label: 'Grid Voltage',
    symbol: 'V',
    min: 200,
    max: 690,
    step: 10,
    unit: 'V',
    category: 'electrical',
    description: 'Grid line-to-line voltage',
  },
  {
    key: 'frequency',
    label: 'Grid Frequency',
    symbol: 'f',
    min: 50,
    max: 60,
    step: 10,
    unit: 'Hz',
    category: 'electrical',
    description: 'Grid frequency',
  },
  {
    key: 'powerRated',
    label: 'Rated Power',
    symbol: 'Pᵣ',
    min: 10,
    max: 500,
    step: 10,
    unit: 'kW',
    category: 'configuration',
    description: 'Inverter rated power',
    hidden: true,
  },
  {
    key: 'energyCapacity',
    label: 'Battery Capacity',
    symbol: 'E',
    min: 20,
    max: 1000,
    step: 20,
    unit: 'kWh',
    category: 'configuration',
    description: 'Battery energy capacity',
    hidden: true,
  },
  {
    key: 'powerSetpoint',
    label: 'Active Power',
    symbol: 'P',
    min: -100,
    max: 100,
    step: 5,
    unit: 'kW',
    category: 'electrical',
    description: 'Active power setpoint (- = charging, + = discharging)',
  },
  {
    key: 'reactiveSetpoint',
    label: 'Reactive Power',
    symbol: 'Q',
    min: -100,
    max: 100,
    step: 5,
    unit: 'kvar',
    category: 'electrical',
    description: 'Reactive power setpoint (- = capacitive/supply, + = inductive/consume)',
  },
  {
    key: 'socInitial',
    label: 'Initial SOC',
    symbol: 'SOC₀',
    min: 0,
    max: 100,
    step: 5,
    unit: '%',
    category: 'configuration',
    description: 'Initial state of charge',
    hidden: true,
  },
  {
    key: 'efficiency',
    label: 'Efficiency',
    symbol: 'η',
    min: 80,
    max: 100,
    step: 1,
    unit: '%',
    category: 'configuration',
    description: 'Round-trip efficiency',
    hidden: true,
  },
  {
    key: 'priorityMode',
    label: 'P-Q Priority',
    symbol: 'Mode',
    min: 0,
    max: 1,
    step: 1,
    unit: '',
    category: 'configuration',
    description: 'Active Power priority or Reactive Power priority',
    options: [
      { value: 'active', label: 'P Priority' },
      { value: 'reactive', label: 'Q Priority' },
    ],
  },
  ...HARMONIC_PARAMETERS,
];

export const BESS_PRESETS: MachinePreset<BessParams>[] = [
  {
    name: 'Grid Support',
    description: 'Pure reactive power for voltage support',
    params: {
      voltage: 400,
      frequency: 50,
      powerRated: 100,
      energyCapacity: 200,
      powerSetpoint: 0,
      reactiveSetpoint: -50,
      socInitial: 50,
      efficiency: 95,
      priorityMode: 'reactive' as const,
    },
  },
  {
    name: 'Peak Shaving',
    description: 'Discharge at unity PF',
    params: {
      voltage: 400,
      frequency: 50,
      powerRated: 100,
      energyCapacity: 200,
      powerSetpoint: 80,
      reactiveSetpoint: 0,
      socInitial: 90,
      efficiency: 95,
      priorityMode: 'active' as const,
    },
  },
  {
    name: 'Load Shifting',
    description: 'Charge during off-peak',
    params: {
      voltage: 400,
      frequency: 50,
      powerRated: 100,
      energyCapacity: 200,
      powerSetpoint: -60,
      reactiveSetpoint: 0,
      socInitial: 20,
      efficiency: 95,
      priorityMode: 'active' as const,
    },
  },
  {
    name: 'Four-Quadrant',
    description: 'Discharge + grid support',
    params: {
      voltage: 400,
      frequency: 50,
      powerRated: 100,
      energyCapacity: 200,
      powerSetpoint: 50,
      reactiveSetpoint: -40,
      socInitial: 70,
      efficiency: 95,
      priorityMode: 'active' as const,
    },
  },
];

export const BESS_CONFIG: MachineConfig<BessParams> = {
  type: 'bess',
  constructor: Bess,
  defaultParams: DEFAULT_BESS_PARAMS,
  parameters: BESS_PARAMETERS,
  presets: BESS_PRESETS,
};
